#!/bin/bash

# set -ex
PATH=${PATH}:/var/vcap/packages/docker/bin/
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock

docker run -i --user "<%= p('user')%>" -t "<%= p('image') %>" \
  <%= if (defined? volume) then "-v " + p('volume') + ":" + p('mount') else "" end %> \
  <%= if (defined? command) then p('command') else "" end %>
