#!/bin/bash

set -e

PATH=${PATH}:/var/vcap/packages/docker/bin/
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock


<% if_p('volume') do |volume| -%>
# Create the docker volume if one is set. Can be run multiple times without error
docker volume create <%= p('volume') %>
<% end -%>
