name: jumpbox

instance_groups:
- name: jumpbox
  instances: 1
  azs:       [z1]
  vm_type:   default
  stemcell:  default
  persistent_disk_type: default
  networks:
    - name: default
  jobs:
    - release: jumpbox
      name: jumpbox
      properties:
        jumpbox:
          users: ((jumpbox_users))
    - release: jumpbox
      name: docker


update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: jumpbox
  version: 4.4.3
  url: https://github.com/cloudfoundry-community/jumpbox-boshrelease/releases/download/v4.4.3/jumpbox-4.4.3.tgz
  sha1: 35953a2bb5c852f196dfbb010856724d4abbf19a
